### ISSUE TITLE
Several variables assigning error

### ISSUE THREAD

**Issue by kaermorchen** [gbprod/tree-sitter-twig#11]
Hi, thanks for your work in this repo.

Twig supports several variables in one [assignment statement](https://twig.symfony.com/doc/3.x/tags/set.html)

But the parser catches errors.

![Screenshot 2023-06-20 at 14-35-05 tree-sitter twig](https://github.com/gbprod/tree-sitter-twig/assets/11972062/8af1ba94-68af-4038-a299-07a5e0732aac)

**Comment by gbprod** [comment]
Interesting, I try to fix it soon !
