### ISSUE TITLE
Highlighting error on twig functions

### ISSUE THREAD

**Issue by Mmasson-01** [gbprod/tree-sitter-twig#9]
When integrating twig functions the highlighting breaks.

# Expected behavior
- Highlighting before and after lines where twig functions are invoked

# Actual behavior
- Highlighting works on some lines, breaks on other lines. 
- Inconsistent behavior across opening and closing tag. See example # 2.

# Configuration
## Treesitter

```lua
local ok, configs = pcall(require, "nvim-treesitter.configs")

if ok then
    configs.setup({
        additional_vim_regex_highlighting = false,
        auto_install = true,
        enable = true,
        ensure_installed = {
            "hcl",
            "astro",
            "bash",
            "css",
            "dockerfile",
            "graphql",
            "go",
            "html",
            "javascript",
            "jsdoc",
            "json",
            "jsonc",
            "lua",
            "markdown",
            "php",
            "python",
            "rust",
            "scss",
            "sql",
            "svelte",
            "toml",
            "tsx",
            "yaml",
            "typescript",
            "twig"
        },
        ignore_install = { "phpdoc" },
        highlight = { enable = true },
        indent = { enable = true },
        autotag = { enable = true },
    })
end
```

# Examples
Installation is flawless and I can get autocompletion for twig macros and stuff. Im using the this boilerplate to test: https://github.com/craftcms/craft  (templates/index.twig)

1. Inside a <style></style> tag
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/39672866/221912547-79c30398-95cb-4bc3-888c-3eca8f12e2b0.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/39672866/221912638-e4d2a24e-770f-464d-98b1-087c64ae1573.png">

2. Inside HTML tag
<img width="972" alt="image" src="https://user-images.githubusercontent.com/39672866/221912896-2cbd6e65-64ea-4c17-8751-f5e5196dd313.png">

- I tried changing all single quote to double quote & vice-versa. Also tried mixing double quote with single quote. 
- I tried all type of opening and closing braces ( "{{ }}", "{% %}", "{%- -%}", "{%~ ~%}", etc. Exact same highlighting behavior

# Comments

I dont fully understand how queries and stuff works so i'm not able to debug and open a MR. Do you have any idea?

**Comment by gbprod** [comment]
Hello @Mmasson-01 and thanks for reporting this issue.
This issue is known and seems to comes from nvim-treesitter, it's about combined injection. You can follow that here : 

 - https://github.com/nvim-treesitter/nvim-treesitter/issues/3497
 - https://github.com/nvim-treesitter/nvim-treesitter/issues/2565

**Comment by gbprod** [comment]
I close this issue as it's not related to this repo...
